name: Autotesting

on:
  push:
    branches:
      - 'Task/*'   # Запускать CI для всех веток, начинающихся с "feature/"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adoptopenjdk'

    - name: Set up Maven
      run: sudo apt-get install maven

    - name: Run tests
      run: mvn clean test

    - name: Generate Allure report
      run: mvn allure:serve
