
name: Java CI Autotesting

on:
  schedule: 
    - cron: "0 9 * * *" # Запуск каждый день в 9 утра
  push:
    branches:
      - "Task_6_Cucumber/Gherkin_CI"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Install Google Chrome
        run: |
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable

      - name: Create conf.properties
        run: |
          mkdir -p src/main/resources
          echo "BASE_URL=${{ secrets.BASE_URL }}" > src/main/resources/conf.properties
          echo "dbHost=${{ secrets.DBHOST }}" >> src/main/resources/conf.properties
          echo "dbName=${{ secrets.DBNAME }}" >> src/main/resources/conf.properties
          echo "dbPass=${{ secrets.DBPASS }}" >> src/main/resources/conf.properties
          echo "dbPort=${{ secrets.DBPORT }}" >> src/main/resources/conf.properties
          echo "dbSchema=${{ secrets.DBSCHEMA }}" >> src/main/resources/conf.properties
          echo "dbUser=${{ secrets.DBUSER }}" >> src/main/resources/conf.properties
          cat src/main/resources/conf.properties

      - name: Running tests
        run: mvn clean test
        continue-on-error: true

      - name: Generate Allure report
        run: |          
          mvn allure:report

      - name: Archive report
        run: |
          cd target/site/allure-maven-plugin
          zip -r allure-report.zip .
          mv allure-report.zip ../../../../allure-report.zip

      - name: List directory contents
        run: ls -la
      
      - name: Send Email with report
        uses: dawidd6/action-send-mail@v4
        with:
          connection_url: smtp://${{ secrets.EMAIL }}:${{ secrets.EMAIL_SMTP_PASS }}@smtp.mail.ru:587
          subject: "Test Report"
          to: kulinkovich.maksim@gmail.com
          from: "Test Reports <${{ secrets.EMAIL }}>"
          body: "Allure report in attachment"
          attachments: target/site/allure-maven-plugin/allure-report.zip
