
name: Java CI Autotesting

on:
  push:
    branches:
      - "Task_6_Cucumber/Gherkin_CI"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create conf.properties from GitHub secrets
        run: |
          touch conf.properties
          echo "BASE_URL=${{ secrets.BASE_URL }}" > $conf.properties
          echo "DBHOST=${{ secrets.DBHOST }}" > $conf.properties
          echo "DBNAME=${{ secrets.DBNAME }}" > $conf.properties
          echo "DBPASS=${{ secrets.DBPASS }}" > $conf.properties
          echo "DBPORT=${{ secrets.DBPORT }}" > $conf.properties
          echo "DBSCHEMA=${{ secrets.DBSCHEMA }}" > $conf.properties
          echo "DBUSER=${{ secrets.DBUSER }}" > $conf.properties
          cat conf.properties 

      - name: Build with Maven
        run: |
          mvn clean test

      - name: Generate Allure report
        run: |
          mvn allure:report
